### ISSUE TITLE
It would be nice to have fgl-arbitrary in Hackage

### ISSUE THREAD

**Issue by rocurley** [haskell/fgl#12]
I'm writing some tests for my code which relies on fgl, and the Arbitrary instance for graphs is very helpful. I've got this repository subtreed into my own so I can use it, but it would be nice to get fgl-arbitrary through Hackage instead.

**Comment by ivan-m** [comment]
It will be once I finish it!

I'm still adding some features to it now as I'm fleshing out the test-suite for fgl itself (e.g. the ability to generate connected undirected graphs).  Once that's done I'll release it along with the new version of fgl.

**Comment by manleyjster** [comment]
+1 Having Arbitrary instances would be awesome. Can't wait for the new version to be released!

**Comment by ivan-m** [comment]
Can people please check the current state of the fgl-arbitrary sub-package; if people are OK with it I'll release it in the next few days.

**Comment by ivan-m** [comment]
Done! http://hackage.haskell.org/package/fgl-arbitrary
