### ISSUE TITLE
fgl-arbitrary-0.1.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [haskell/fgl#17]
Citing from http://hydra.cryp.to/build/943341/log/raw:

~~~~
Data/Graph/Inductive/Arbitrary.hs:40:70:
    Module ‘Data.Graph.Inductive.Graph’ does not export ‘toEdge’
~~~~

**Comment by ivan-m** [comment]
*bangs head against desk*

That's what I get for trying to make a release for people that requested it, before remembering that it was using features of fgl I haven't released yet :s

So I guess I better release a newer version of fgl ASAP...

**Comment by peti** [comment]
Ping?

**Comment by ivan-m** [comment]
I'm hoping to get the new release of fgl + fgl-arbitrary out by this weekend; the only things left to do is try a new approach to the `Connected` arbitrary wrapper and hopefully merge in @scolobb's pull requests (#2 and #3) if they're done in time.

**Comment by ivan-m** [comment]
Sorry for the noise here: it seems commits to a testing branch pop up here as well :s
