### ISSUE TITLE
fgl-5.5.2.0 doesn't compile with old versions of GHC 

### ISSUE THREAD

**Issue by peti** [haskell/fgl#19]
`ghc-7.0.4`: http://hydra.cryp.to/build/994563/log/raw
`ghc-7.2.2`: http://hydra.cryp.to/build/994341/log/raw

The problem seems to be:

~~~
Data/Graph/Inductive/PatriciaTree.hs:115:16:
    Could not deduce (NFData (GraphRep a b))
      arising from a use of `rnf'
    from the context (NFData a, NFData b)
      bound by the instance declaration
      at Data/Graph/Inductive/PatriciaTree.hs:114:10-48
    Possible fix:
      add (NFData (GraphRep a b)) to the context of
        the instance declaration
      or add an instance declaration for (NFData (GraphRep a b))
    In the expression: rnf g
    In an equation for `rnf': rnf (Gr g) = rnf g
    In the instance declaration for `NFData (Gr a b)'
~~~

**Comment by ivan-m** [comment]
OK, I obviously didn't use old enough versions for the Travis-CI builds.

It looks like the problem is that the version of containers that ships with older versions of GHC doesn't have support for `Generic`.

**Comment by ivan-m** [comment]
Of course, by "`Generic`", I meant "`NFData`" :p

Just testing the fix on Travis-CI; once it's done I'll make a release.
