### ISSUE TITLE
`insEdges` not specialized

### ISSUE THREAD

**Issue by treeowl** [haskell/fgl#26]
Daniel Martin discovered that [`insEdges` is not being properly specialized](http://stackoverflow.com/q/35557964/1477667), and therefore the `insEdge` rewrite rule for Patricia trees is not firing. The fix was to mark `insEdges` `INLINABLE`. I would also recommend marking `insEdge` `NOINLINE [0]` or similar to make sure it doesn't inline prematurely and hide from the rule.

**Comment by fizbin** [comment]
Note that this same issue applies to `insNodes`, which should also be tagged `INLINABLE`.

**Comment by ivan-m** [comment]
I'll have a look at this; ta.
