### ISSUE TITLE
label' :: gr a b -> Edge -> Maybe b ?

### ISSUE THREAD

**Issue by delanoe** [haskell/fgl#37]
Hello,
looking at the Martin Erwigs' paper and the code in this repo, I do not see a function that would return the label of LEdge given the graph and the Edge. It is a basic function so I wonder if it was somewhere already.

More precisions about such function (label for edge):
label':: gr a b -> Edge -> Maybe b
Given a Graph and an Edge, gives the label of the edge if it exists.

I wonder if the NodeMap file tries to provide such utility.
Many thanks in advance for your help dealing with such a basic question.
By the way many thanks for maintaining this wonderful library.

**Comment by ivan-m** [comment]
Untested:

```haskell
import Data.List

label' :: (Graph gr) => gr a b -> Edge -> Maybe b
label' gr (u,v) = lookup v (lsuc gr u)
```

Not sure if it's worth adding something like this to the library; will think about this.

**Comment by delanoe** [comment]
Yes, I think it is worth adding such basic function to ease first adoption of the library (TMHO).

**Comment by ivan-m** [comment]
Pull Requests welcome :)

But it's too easy to have lots of little functions making it difficult to find any particular one.

**Comment by delanoe** [comment]
Le 26 juil. 16, vers 15:34, Ivan Lazar Miljenovic ecrivait:
> Pull Requests welcome :)

Ok.

> But it's too easy to have lots of little functions making it difficult to find
> any particular one.

You are right, I am thinking about the right implementation to avoid
unnecessary functions/code.


-- 
Alexandre Delanoë
