### ISSUE TITLE
prettyPrinter is sufficiently inaccurate as to be useless

### ISSUE THREAD

**Issue by fizbin** [haskell/fgl#9]
The `prettyPrint` function drops any outgoing edge that it encounters "out of order":

```
*Main> import qualified Data.Graph.Inductive as G
*Main G> import qualified Data.Graph.Inductive.PatriciaTree as Pt
*Main G Pt> G.prettyPrint (G.mkGraph [(x, ()) | x <- [0..6]] [(0,6,()),(2,1,()),(3,2,()),(4,3,()),(5,4,()),(6,5,())] :: Pt.Gr () ())
0:()->[((),6)]
1:()->[]
2:()->[]
3:()->[]
4:()->[]
5:()->[]
6:()->[]
```

This makes it nearly useless for debugging most complicated graphs, and the only graphs it can even possibly print correctly are DAGs.

**Comment by fizbin** [comment]
For the record, here's the code I added to my project to get debugging output after discovering that `prettyPrint` was leading me astray; you can take this and adapt it at will:
```
prettyG :: (G.Graph gr) =>
           (a -> String) -> (b -> String) -> gr a b -> String
prettyG nodeLabeler edgeLabeler gr =
  concatMap (\n ->
              let (_, _, lbl, outs) = G.context gr n
              in formatInt n 4 ++ ":" ++ nodeLabeler lbl ++ "->[" ++
                 intercalate "," (map (\(b, m) ->
                                         "(" ++ edgeLabeler b ++ ","
                                         ++ show m ++ ")") outs) ++ "]\n")
  $ G.nodes gr
  where
    formatInt i width = let s = show i
                        in if length s < width
                           then reverse $ take width (reverse s ++ repeat ' ')
                           else s
```

**Comment by ivan-m** [comment]
So the pretty-printer is my adaptation of the old `Show` instances but trying to make it so that it worked for any instance of `Graph`... except I did it wrong :s

Apart from the missing information, is there anything in particular you don't like about the format?  I notice that you've tried to do padding, etc. in yours, but I'd prefer to avoid doing anything like that without use of a proper pretty-printing library.

**Comment by ivan-m** [comment]
OK, will this do for a pretty-printer's results?

```
λ> let g = mkGraph [(x, ()) | x <- [0..6]] [(0,6,()),(2,1,()),(3,2,()),(4,3,()),(5,4,()),(6,5,())] :: Gr () ()
λ> prettyPrint g
0:()->[((),6)]
1:()->[]
2:()->[((),1)]
3:()->[((),2)]
4:()->[((),3)]
5:()->[((),4)]
6:()->[((),5)]
```

This is achieved by changing the definition of `prettify` from:
```.haskell
prettify g = ufold showsContext id g ""
  where
    ...
```
to:
```.haskell
prettify g = foldr (showsContext . context g) id (nodes g) ""
  where
    ...
```

**Comment by fizbin** [comment]
Yeah, that's good. The main point is to do something using `context g` over the result of `nodes g` (so that you get the full context for each node) instead of using `ufold`, which only does edges on one side (and that side is unpredictable).
